# Generated by Django 4.1.5 on 2023-01-17 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='buy_price',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='exp_date',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='in_stock',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='mfg_date',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='sell_price',
            field=models.CharField(max_length=255),
        ),
    ]
