# Generated by Django 4.1.5 on 2023-01-17 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0002_alter_product_buy_price_alter_product_exp_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='buy_price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='exp_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='in_stock',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='mfg_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='sell_price',
            field=models.FloatField(),
        ),
    ]
