# Generated by Django 4.1.5 on 2023-01-17 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0003_alter_product_buy_price_alter_product_exp_date_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='employeesalary',
            table='employee_salary',
        ),
    ]
