# Generated by Django 4.1.5 on 2023-01-19 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0004_alter_employeesalary_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdetails',
            name='in_stock',
            field=models.IntegerField(max_length=255),
        ),
    ]
