# Generated by Django 4.1.5 on 2023-01-19 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0005_alter_productdetails_in_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdetails',
            name='in_stock',
            field=models.IntegerField(),
        ),
    ]
